services:
  - type: web
    name: societypro
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: CLOUD_DB_HOST
        sync: false
      - key: CLOUD_DB_PORT
        sync: false
      - key: CLOUD_DB_USER
        sync: false
      - key: CLOUD_DB_PASSWORD
        sync: false
      - key: CLOUD_DB_NAME
        sync: false
      - key: SSL_CA_PATH
        value: ca.pem
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
